spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog-test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug

external:
  api:
    name: kakao
    api-key: 05688d38d8ddb251505f898072f0dc1d