spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog-test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug

external:
  apis:
    kakao:
      blog-search-api:
        url: https://dapi.kakao.com/v2/search/blog
        api-key: KakaoAK 05688d38d8ddb251505f898072f0dc1d